import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.scss";
import Movies from "@/components/Movie";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <section className={styles.production}>
            <header>
              <h1 className={styles.title}>Patel Production</h1>
              <p className={styles.subtitle}>
                Crafting Cinematic Journeys: From Imagination to Reality, We
                Bring Stories to Life on the Silver Screen.
              </p>
            </header>
          </section>
          <Movies />
        </main>
      </div>
    </>
  );
}
